# Generated by Django 5.0.1 on 2024-01-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('pending', 'Pending')], default='pending'),
        ),
    ]
